# Generated by Django 4.1.3 on 2022-11-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id_personaje', models.AutoField(db_column='id_personaje', primary_key=True, serialize=False)),
                ('fecha_cumpleaños', models.DateField(blank=True, null=True)),
                ('characterID', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=20)),
                ('edad', models.CharField(blank=True, max_length=10, null=True)),
                ('region', models.CharField(max_length=20)),
                ('vision', models.CharField(max_length=10)),
                ('afiliacion', models.CharField(blank=True, max_length=20)),
                ('constelacion', models.CharField(max_length=30)),
                ('genero', models.CharField(blank=True, max_length=10, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos')),
            ],
        ),
    ]
